-- 017_create_order_with_items_rpc
--
-- Atomic order creation: snapshots the customer's primary address into
-- delivery_address_snapshot, computes subtotal from items, inserts the
-- order + every item + the initial pending status event in a single
-- transaction. Failure anywhere → rollback.
--
-- Faz 1 admin concurrency is low; this is the simplest correct shape
-- without hand-rolling sequential inserts + cleanup like the customer
-- create path. SECURITY INVOKER so RLS still gates access.

create or replace function create_order_with_items(
  p_customer_id uuid,
  p_scheduled_for date,
  p_time_slot time_slot,
  p_payment_method payment_method,
  p_delivery_notes text,
  p_delivery_fee_minor bigint,
  p_created_by uuid,
  p_items jsonb
) returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_order_id uuid;
  v_address_snapshot jsonb;
  v_subtotal bigint := 0;
  v_address_row addresses%rowtype;
  v_total_count int;
begin
  -- Snapshot the customer's primary address.
  select * into v_address_row
  from addresses a
  where a.customer_id = p_customer_id and a.is_primary
  limit 1;

  if not found then
    raise exception 'customer % has no primary address', p_customer_id
      using errcode = 'P0001';
  end if;

  v_address_snapshot := jsonb_build_object(
    'raw_text',     v_address_row.raw_text,
    'description',  v_address_row.description,
    'lat',          v_address_row.lat,
    'lng',          v_address_row.lng,
    'accuracy',     v_address_row.accuracy::text,
    'source',       v_address_row.source::text,
    'city',         v_address_row.city,
    'district',     v_address_row.district
  );

  -- Validate items shape + compute subtotal in one pass.
  select count(*) into v_total_count from jsonb_array_elements(p_items);
  if v_total_count = 0 then
    raise exception 'order needs at least one item'
      using errcode = 'P0001';
  end if;

  select coalesce(sum((x.quantity * x.unit_price_minor)::bigint), 0)
    into v_subtotal
  from jsonb_to_recordset(p_items) as x(
    quantity numeric,
    unit_price_minor bigint
  );

  -- Insert the order. order_number is generated by the column default
  -- (next_order_number sequence). total_minor is a generated column.
  insert into orders (
    customer_id,
    scheduled_for,
    time_slot,
    payment_method,
    delivery_notes,
    subtotal_minor,
    delivery_fee_minor,
    delivery_address_snapshot,
    created_by,
    source
  ) values (
    p_customer_id,
    p_scheduled_for,
    p_time_slot,
    p_payment_method,
    p_delivery_notes,
    v_subtotal,
    coalesce(p_delivery_fee_minor, 0),
    v_address_snapshot,
    p_created_by,
    'admin_manual'
  )
  returning id into v_order_id;

  -- Insert items.
  insert into order_items (
    order_id, product_key, quantity, unit_price_minor, product_snapshot
  )
  select
    v_order_id,
    x.product_key,
    x.quantity,
    x.unit_price_minor,
    x.product_snapshot
  from jsonb_to_recordset(p_items) as x(
    product_key text,
    quantity numeric,
    unit_price_minor bigint,
    product_snapshot jsonb
  );

  -- Initial status event — every order's first audit row.
  insert into order_status_events (order_id, from_status, to_status, actor_id)
  values (v_order_id, null, 'pending', p_created_by);

  return v_order_id;
end;
$$;

revoke all on function create_order_with_items(
  uuid, date, time_slot, payment_method, text, bigint, uuid, jsonb
) from public;
grant execute on function create_order_with_items(
  uuid, date, time_slot, payment_method, text, bigint, uuid, jsonb
) to authenticated;
